# In netlify.toml

[build]
  base = "LMS_Frontend"
  
  # FIX: Use npm install with the legacy flag before running the build
  command = "npm install --legacy-peer-deps && npm run build" 
  
  publish = "build"